spring.application.name=moneta-core
# Dados da Conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/moneta_db
spring.datasource.username=postgres
spring.datasource.password=let_Monako

# Hibernate - O "Pedreiro" do Banco de Dados.
# update: O Hibernate cria as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect